# Generated by Django 3.0.5 on 2020-12-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='healthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userToken', models.CharField(max_length=250)),
                ('timeStamp', models.DateTimeField()),
                ('heartRate', models.IntegerField()),
                ('stepsCount', models.IntegerField()),
                ('stationaryLabelCount', models.IntegerField()),
                ('walkingLabelCount', models.IntegerField()),
                ('runningLabelCount', models.IntegerField()),
                ('automotiveLabelCount', models.IntegerField()),
                ('cyclingLabelCount', models.IntegerField()),
                ('unknownLabelCount', models.IntegerField()),
                ('distanceCovered', models.FloatField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=250)),
                ('bloodType', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'healthData',
                'ordering': ['userToken', 'timeStamp'],
            },
        ),
    ]
