# Generated by Django 3.0.6 on 2020-11-09 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medical_records', models.CharField(max_length=250)),
                ('physician_name', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kids_name', models.CharField(max_length=250)),
                ('kids_dob', models.CharField(max_length=250)),
                ('guardian', models.CharField(max_length=250)),
                ('kids_weight', models.IntegerField()),
                ('kids_height', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnxietyData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('heartbeat', models.CharField(max_length=250)),
                ('bp', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anxiety', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
